<a href="https://colab.research.google.com/github/Ardatatl33/turk-yeyapayzekaakademisi_bootcamp/blob/main/VeriBilimiEgitim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Veri Bilimi

## veri setini tanıma

In [177]:
import pandas as pd

In [178]:
# veri yükleme
df = pd.read_csv("/content/e_ticaret_veri_seti.csv")

In [179]:
df.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,49.9,Kredi Kartı,Yeni,3.0,5.0,Hayır,0.220,443.68
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,29.9,Banka Kartı,VIP,4.0,1.0,Hayır,0.361,2685.17
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,29.9,Kredi Kartı,Mevcut,6.0,2.0,Hayır,0.348,304.47
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,49.9,Kapıda Ödeme,Yeni,3.0,5.0,Hayır,0.250,1023.80
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03

In [180]:
df.tail()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
1423,SIP101093,MUS1187,2024-06-08 20:42:00,İstanbul,Marmara,Spor,Yoga Matı,1,772.23,0.00,29.9,Kredi Kartı,Mevcut,3.0,2.0,Hayır,0.275,802.13
1424,SIP101193,MUS1297,2025-11-06 08:17:00,Gaziantep,Güneydoğu Anadolu,Spor,Suluk,2,187.03,0.00,59.9,Kredi Kartı,Yeni,2.0,4.0,Evet,0.243,433.96
1425,SIP101210,MUS1122,2025-03-07 09:07:00,NaN,Marmara,Elektronik,Webcam,4,894.47,0.10,49.9,Kredi Kartı,Mevcut,3.0,5.0,Hayır,0.355,3269.99
1426,SIP101060,MUS1189,2025-04-19 21:52:00,Kocaeli,Marmara,Kitap,Veri Bilimi 101,2,248.55,0.05,59.9,banka karti,Yeni,4.0,3.0,Hayır,0.373,532.14
1427,SIP100642,MUS1289,2024-09-22 16:36:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,424.84,0.20,0.0,Dijital Cüzdan,Yeni,2.0,4.0,Hayır,0.317,339.87

In [181]:
# Veri setinin boyutunu ve sütunlarını kontrol etme
satir_sayisi = df.shape[0]
sutun_sayisi = df.shape[1]

In [182]:
print(satir_sayisi)
print(sutun_sayisi)

1428
18

In [183]:
for i , sutun in enumerate(df.columns , start=1):
  print(f"{i}.{sutun}")

1.siparis_id
2.musteri_id
3.siparis_tarihi
4.sehir
5.bolge
6.kategori
7.urun_adi
8.adet
9.birim_fiyat
10.indirim_orani
11.kargo_ucreti
12.odeme_turu
13.musteri_tipi
14.teslimat_gunu
15.musteri_puani
16.iade_durumu
17.kar_marji_orani
18.toplam_tutar

In [184]:
# 4 veri setinin genel bilgisini inceleme
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1428 entries, 0 to 1427
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   siparis_id       1428 non-null   object
 1   musteri_id       1428 non-null   object
 2   siparis_tarihi   1428 non-null   object
 3   sehir            1403 non-null   object
 4   bolge            1428 non-null   object
 5   kategori         1428 non-null   object
 6   urun_adi         1428 non-null   object
 7   adet             1428 non-null   int64
 8   birim_fiyat      1428 non-null   float64
 9   indirim_orani    1412 non-null   float64
 10  kargo_ucreti     1428 non-null   float64
 11  odeme_turu       1393 non-null   object
 12  musteri_tipi     1386 non-null   object
 13  teslimat_gunu    1400 non-null   float64
 14  musteri_puani    1372 non-null   float64
 15  iade_durumu      1428 non-null   object
 16  kar_marji_orani  1428 non-null   float64
 17  toplam_tutar     1428 non-null   float64
dtypes: float64(7), int64(1), object(10)
memory usage: 200.9+ KB

In [185]:
#5 özet istatistikleri görüntüleme
df.describe()

,adet,birim_fiyat,indirim_orani,kargo_ucreti,teslimat_gunu,musteri_puani,kar_marji_orani,toplam_tutar
count,1428.000000,1428.000000,1412.000000,1428.000000,1400.000000,1372.000000,1428.000000,1428.000000
mean,2.136555,658.477654,0.052054,39.725140,3.370714,4.002187,0.302799,1370.590336
std,2.015770,1042.414639,0.060115,14.185017,1.825990,1.096707,0.069795,2961.689500
min,1.000000,93.110000,0.000000,0.000000,1.000000,0.000000,0.180000,89.680000
25%,1.000000,199.185000,0.000000,29.900000,2.000000,3.000000,0.244750,323.855000
50%,2.000000,287.120000,0.050000,39.900000,3.000000,4.000000,0.305000,669.135000
75%,3.000000,819.177500,0.100000,49.900000,4.000000,5.000000,0.362000,1390.950000
max,38.000000,18145.230000,0.200000,59.900000,31.000000,7.000000,0.420000,63870.200000

In [186]:
#6. Veri tiplerini kontrol etme
df.dtypes

siparis_id          object
musteri_id          object
siparis_tarihi      object
sehir               object
bolge               object
kategori            object
urun_adi            object
adet                 int64
birim_fiyat        float64
indirim_orani      float64
kargo_ucreti       float64
odeme_turu          object
musteri_tipi        object
teslimat_gunu      float64
musteri_puani      float64
iade_durumu         object
kar_marji_orani    float64
toplam_tutar       float64
dtype: object

In [187]:
# 7 sayısal ve kategorik sütunları ayırma
sayısal_sutunlar = df.select_dtypes(include=["int64","float64"]).columns
sayısal_sutunlar

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='object')

In [188]:
kategorik_sutunlar = df.select_dtypes(include=["object"]).columns
kategorik_sutunlar

Index(['siparis_id', 'musteri_id', 'siparis_tarihi', 'sehir', 'bolge',
       'kategori', 'urun_adi', 'odeme_turu', 'musteri_tipi', 'iade_durumu'],
      dtype='object')

In [189]:
#8. benzersiz ( unique ) değer sayılarının incelenmesi
for sütun in df.columns:
  print((f"{sütun} : {df[sütun].nunique()}"))

siparis_id : 1400
musteri_id : 422
siparis_tarihi : 1398
sehir : 19
bolge : 6
kategori : 15
urun_adi : 30
adet : 10
birim_fiyat : 1381
indirim_orani : 5
kargo_ucreti : 5
odeme_turu : 12
musteri_tipi : 7
teslimat_gunu : 11
musteri_puani : 8
iade_durumu : 2
kar_marji_orani : 241
toplam_tutar : 1397

## kayıp veri (missing value)

In [190]:
import pandas as pd
df = pd.read_csv("/content/e_ticaret_veri_seti.csv")

In [191]:
#eksik verileri  tespit etme
df.isnull().sum()

siparis_id          0
musteri_id          0
siparis_tarihi      0
sehir              25
bolge               0
kategori            0
urun_adi            0
adet                0
birim_fiyat         0
indirim_orani      16
kargo_ucreti        0
odeme_turu         35
musteri_tipi       42
teslimat_gunu      28
musteri_puani      56
iade_durumu         0
kar_marji_orani     0
toplam_tutar        0
dtype: int64

In [192]:
# eksik veri oranlarını hesapla
eksik_sayilari = df.isnull().sum()
eksik_oranlari = 100 * (eksik_sayilari / len(df))
eksik_oranlari

siparis_id         0.000000
musteri_id         0.000000
siparis_tarihi     0.000000
sehir              1.750700
bolge              0.000000
kategori           0.000000
urun_adi           0.000000
adet               0.000000
birim_fiyat        0.000000
indirim_orani      1.120448
kargo_ucreti       0.000000
odeme_turu         2.450980
musteri_tipi       2.941176
teslimat_gunu      1.960784
musteri_puani      3.921569
iade_durumu        0.000000
kar_marji_orani    0.000000
toplam_tutar       0.000000
dtype: float64

In [193]:
#eksik veri içeren satırları incele
eksik_veriler = df[df.isnull().any(axis = 1)]
eksik_veriler.head(10)

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
19,SIP100677,MUS1148,2024-07-11 16:24:00,Adana,Akdeniz,Spor,Dambıl Seti,4,1517.65,0.0,29.9,Kapıda Ödeme,Mevcut,3.0,NaN,Hayır,0.311,6100.50
33,SIP101126,MUS1406,2024-09-11 20:05:00,Mersin,Akdeniz,Elektronik,Bluetooth Hoparlör,1,1159.89,0.1,39.9,Kredi Kartı,NaN,2.0,4.0,Hayır,0.204,1083.80
50,SIP101040,MUS1386,2025-04-01 09:30:00,Trabzon,Karadeniz,Spor,Dambıl Seti,1,1554.15,0.0,49.9,Banka Kartı,NaN,4.0,5.0,Hayır,0.217,1604.05
60,SIP100890,MUS1271,2024-11-07 19:47:00,İzmir,Ege,Kitap,Girişimcilik,4,216.38,NaN,49.9,Kredi Kartı,Yeni,1.0,3.0,Hayır,0.199,915.42
61,SIP101317,MUS1060,2024-09-05 20:49:00,NaN,Akdeniz,Ev ve Yaşam,Saklama Kutusu,1,233.63,0.1,29.9,Dijital Cüzdan,Yeni,5.0,2.0,Hayır,0.385,240.17
70,SIP100715,MUS1033,2024-11-10 21:50:00,İstanbul,Marmara,Ev ve Yaşam,Termos,1,552.05,0.0,39.9,NaN,Mevcut,2.0,3.0,Hayır,0.185,591.95
82,SIP100807,MUS1431,2025-01-07 14:12:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,451.28,0.0,49.9,Kredi Kartı,NaN,4.0,5.0,Hayır,0.315,501.18
84,SIP100679,MUS1310,2024-05-20 18:51:00,İzmir,Ege,Ev ve Yaşam,Termos,2,477.62,0.0,49.9,Kredi Kartı,Mevcut,NaN,4.0,Hayır,0.323,1005.14
86,SIP101071,MUS1131,2024-09-18 12:24:00,NaN,İç Anadolu,Elektronik,Powerbank,1,816.74,0.0,39.9,Banka Kartı,Yeni,3.0,5.0,Hayır,0.301,856.64
92,SIP101366,MUS1347,2025-03-04 14:00:00,Bursa,Marmara,Ev ve Yaşam,Organizer,1,272.40,0.0,29.9,Kredi Kartı,Mevcut,1.0,NaN,Hayır,0.212,302.30

In [194]:
#eksik veri silme
df_silinen = df.dropna()

In [195]:
df_silinen.shape

(1239, 18)

In [196]:
#6. sayısal eksik verilerin ortalamayla doldurulması
df_ortalama = df.copy()
sayisal_sutunlar = df_ortalama.select_dtypes(include=["int64","float64"]).columns
sayisal_sutunlar

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='object')

In [197]:
for sütun in sayisal_sutunlar:
 df_ortalama[sütun] = df_ortalama[sütun].fillna(df_ortalama[sütun].mean())

In [198]:
df_ortalama[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [199]:
# sayısal eksik verilerin medyan doldurulması
df_medyan = df.copy()
for sütun in sayisal_sutunlar:
  df_medyan[sütun] = df_medyan[sütun].fillna(df_medyan[sütun].median())
df_medyan[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [200]:
# sayısal eksik verilerin mod doldurulması
df_mod = df.copy()
for sütun in sayisal_sutunlar:
  mod_degeri = df_mod[sütun].mode()[0]
  df_mod[sütun] = df_medyan[sütun].fillna(mod_degeri)
df_mod[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [201]:
# kategorik verileri mod ile doldurma
df_kategorik = df.copy()
kategorik_sutunlar = df_kategorik.select_dtypes(include=["object"]).columns
kategorik_sutunlar

Index(['siparis_id', 'musteri_id', 'siparis_tarihi', 'sehir', 'bolge',
       'kategori', 'urun_adi', 'odeme_turu', 'musteri_tipi', 'iade_durumu'],
      dtype='object')

In [202]:
for sütun in kategorik_sutunlar:
  mod_degeri = df_kategorik[sütun].mode()[0]
  df_kategorik[sütun] = df_kategorik[sütun].fillna(mod_degeri)
df_kategorik[kategorik_sutunlar].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [203]:
# kategorik eksik verileri sabitle doldurma
df_sabit_kategorik = df.copy()
for sütun in kategorik_sutunlar:
  df_sabit_kategorik[sütun] = df_sabit_kategorik[sütun].fillna("Belirtilmemiş")
df_sabit_kategorik[kategorik_sutunlar].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [204]:
from numpy import median
df_guncel = df.copy()
for sutun in sayisal_sutunlar:
  df_guncel[sutun] = df_guncel[sutun].fillna(df[sutun].median())

In [205]:
for sutun in kategorik_sutunlar:
  mod_degeri = df_guncel[sutun].mode()[0]
  df_guncel[sutun] = df_guncel[sutun].fillna(mod_degeri)

In [206]:
df_guncel.isnull().sum()

siparis_id         0
musteri_id         0
siparis_tarihi     0
sehir              0
bolge              0
kategori           0
urun_adi           0
adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
odeme_turu         0
musteri_tipi       0
teslimat_gunu      0
musteri_puani      0
iade_durumu        0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [207]:
# kaydetme
kayıt_veri_seti = "eksik_veri_seti_düzenlendi.csv"
df_guncel.to_csv(kayıt_veri_seti, index=False)

## Veri Seti Düzenleme

In [208]:
import pandas as pd
df = pd.read_csv("/content/eksik_veri_seti_düzenlendi.csv")

In [209]:
#veri tiplerini incelemek
df.dtypes

siparis_id          object
musteri_id          object
siparis_tarihi      object
sehir               object
bolge               object
kategori            object
urun_adi            object
adet                 int64
birim_fiyat        float64
indirim_orani      float64
kargo_ucreti       float64
odeme_turu          object
musteri_tipi        object
teslimat_gunu      float64
musteri_puani      float64
iade_durumu         object
kar_marji_orani    float64
toplam_tutar       float64
dtype: object

In [210]:
#sayısal ve kategorik sütunları belirleme
sayisal_sutunlar = df.select_dtypes(include=["int64","float64"]).columns.to_list()
sayisal_sutunlar

['adet',
 'birim_fiyat',
 'indirim_orani',
 'kargo_ucreti',
 'teslimat_gunu',
 'musteri_puani',
 'kar_marji_orani',
 'toplam_tutar']

In [211]:
kategorik_sutunlar = df.select_dtypes(include=["object"]).columns.to_list()
kategorik_sutunlar

['siparis_id',
 'musteri_id',
 'siparis_tarihi',
 'sehir',
 'bolge',
 'kategori',
 'urun_adi',
 'odeme_turu',
 'musteri_tipi',
 'iade_durumu']

In [212]:
# 4. sipariş tarih sütunununu datetime tipine dönüştürme (string -> datetime)
df["siparis_tarihi"] = pd.to_datetime(df["siparis_tarihi"])
df["siparis_tarihi"].dtype

dtype('<M8[ns]')

In [213]:
df.dtypes

siparis_id                 object
musteri_id                 object
siparis_tarihi     datetime64[ns]
sehir                      object
bolge                      object
kategori                   object
urun_adi                   object
adet                        int64
birim_fiyat               float64
indirim_orani             float64
kargo_ucreti              float64
odeme_turu                 object
musteri_tipi               object
teslimat_gunu             float64
musteri_puani             float64
iade_durumu                object
kar_marji_orani           float64
toplam_tutar              float64
dtype: object

In [214]:
df["siparis_yili"] = df["siparis_tarihi"].dt.year
df["siparis_ayi"] = df["siparis_tarihi"].dt.month
df["siparis_günü"] = df["siparis_tarihi"].dt.day
df["haftanin_günü"] = df["siparis_tarihi"].dt.day_name()

In [215]:
df.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_günü,haftanin_günü
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,...,Yeni,3.0,5.0,Hayır,0.220,443.68,2024,1,13,Saturday
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,...,VIP,4.0,1.0,Hayır,0.361,2685.17,2025,3,17,Monday
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,...,Mevcut,6.0,2.0,Hayır,0.348,304.47,2025,6,3,Tuesday
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,...,Yeni,3.0,5.0,Hayır,0.250,1023.80,2024,8,10,Saturday
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday

In [216]:
# kategorik sütunları kategori tipine dönüştürme
kategorik_degisim_sütunlar = [
    "sehir",
    "kategori",
    "urun_adi",
    "odeme_turu",
    "musteri_tipi",
    "haftanin_günü"
]

In [217]:
for sütun in kategorik_degisim_sütunlar:
  df[sütun] = df[sütun].astype("category")

In [218]:
df.dtypes

siparis_id                 object
musteri_id                 object
siparis_tarihi     datetime64[ns]
sehir                    category
bolge                      object
kategori                 category
urun_adi                 category
adet                        int64
birim_fiyat               float64
indirim_orani             float64
kargo_ucreti              float64
odeme_turu               category
musteri_tipi             category
teslimat_gunu             float64
musteri_puani             float64
iade_durumu                object
kar_marji_orani           float64
toplam_tutar              float64
siparis_yili                int32
siparis_ayi                 int32
siparis_günü                int32
haftanin_günü            category
dtype: object

In [219]:
df.to_csv("e_ticaret_veri_seti_düzenlendi.csv")

## Tekrarlayan ve Tutarsız kayıtlar
Amaç :
  1. Veri setindeki tekrarlayan ve tutarsız verileri tepit edip temizlemek
  2. Eğitimde kullanılan güncel verileri kaydetmek

Adımlar:
  1. Veri setini yükle
  2. Tekrarlayan kayıtları tespit etmek
  3. Tekrarlayan kayıtları incelemek
  4. Tekrarlayan kayıtları temizlemek
  5. Tutarsız kategorik değerleri incelemek
  6. Şehir sutunundaki tutarsız değerleri düzeltmek
  7. Kategori sutunundaki tutarsız değerleri düzeltmek
  8. Ödeme Türü sutunundaki tutarsız değerleri düzeltmek
  9. Müşteri Tipi sutunundaki tutarsız değerleri düzeltmek
  10. Mantıksal olarak hatalı kayıtları incele
  11. Mantıksal olarak hatalı kayıtları temizleme
  12. Temizlenmiş veri setini kaydetme

In [220]:
import pandas as pd

In [221]:
df = pd.read_csv("/content/e_ticaret_veri_seti_veri_tipleri_duzenlendi.csv")

In [222]:
# Tekrarlayan kayıtları tespit etmek
tekrarlayan_kayitlar = df[df.duplicated()]
len(tekrarlayan_kayitlar)

28

In [223]:
# Tekrarlayan kayıtları incelemek
tekrarlayan_kayitlar.head(10)

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
174,SIP100479,MUS1099,2025-06-10 20:32:00,İstanbul,Marmara,Kozmetik,Güneş Kremi,3,455.19,0.00,...,Yeni,1.0,5.0,Hayır,0.200,1415.47,2025,6,10,Tuesday
315,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday
324,SIP100533,MUS1128,2024-11-19 14:22:00,Trabzon,Karadeniz,Kitap,Python Notları,2,225.82,0.00,...,Yeni,4.0,5.0,Hayır,0.234,491.54,2024,11,19,Tuesday
613,SIP100725,MUS1146,2025-05-24 10:10:00,Kocaeli,Marmara,Kitap,Zaman Yönetimi,2,154.18,0.05,...,Yeni,3.0,5.0,Hayır,0.385,342.84,2025,5,24,Saturday
637,SIP100940,MUS1032,2025-03-25 20:06:00,Samsun,Karadeniz,Kozmetik,Serum,1,507.46,0.15,...,Mevcut,3.0,4.0,Evet,0.402,471.24,2025,3,25,Tuesday
650,SIP100985,MUS1436,2025-12-18 21:45:00,Konya,İç Anadolu,Spor,Suluk,2,203.15,0.15,...,Mevcut,4.0,4.0,Hayır,0.277,395.26,2025,12,18,Thursday
727,SIP100052,MUS1346,2025-03-16 20:37:00,İstanbul,Marmara,Ofis,Mekanik Klavye,3,2052.67,0.10,...,Yeni,3.0,4.0,Hayır,0.398,5592.11,2025,3,16,Sunday
733,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,...,Mevcut,6.0,2.0,Hayır,0.348,304.47,2025,6,3,Tuesday
769,SIP100779,MUS1354,2025-12-05 11:19:00,İstanbul,Marmara,Kitap,Python Notları,4,219.14,0.00,...,Yeni,18.0,5.0,Evet,0.408,906.46,2025,12,5,Friday
808,SIP100234,MUS1204,2025-03-03 22:53:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Bluetooth Hoparlör,1,1220.47,0.05,...,VIP,2.0,3.0,Hayır,0.267,1209.35,2025,3,3,Monday

In [224]:
# 4.tekrarlayan kayıtları temizlemek
df = df.drop_duplicates()
df.shape

(1400, 22)

In [225]:
# 5. Tutarsız kategorik değerleri incelemek
df["sehir"].unique()

array(['İstanbul', 'Gaziantep', 'Kayseri', 'Antalya', 'Konya', 'Ankara',
       'Bursa', 'Trabzon', 'Adana', 'Mersin', 'Kocaeli', 'İzmir',
       'Eskişehir', 'Samsun', 'istanbul', 'ankara', 'Istanbul',
       'gaziantep', 'Izmir'], dtype=object)

In [226]:
df["kategori"].unique()

array(['Kozmetik', 'Spor', 'Kitap', 'Elektronik', 'Ofis', 'ofis',
       'Ev ve Yaşam', 'Elektronik ', 'spor', 'kozmetık', 'ev ve yaşam',
       'kitap', 'Kozmetik ', 'elektronik', 'Ev&Yaşam'], dtype=object)

In [227]:
df["odeme_turu"].unique()

array(['Kredi Kartı', 'Banka Kartı', 'Kapıda Ödeme', 'Dijital Cüzdan',
       'Havale/EFT', 'Kart', 'kredi kartı', 'dijital cüzdan', 'eft',
       'banka karti', 'Kapida Odeme', 'Havale'], dtype=object)

In [234]:
#yardımcı fonksiyon : metinleri normalize edelim
#büyük küçük harf dönüşümleri, boşlukların kaldırılması, Türkçe karakter kaynaklı farkların düzeltilmesi
def metin_normalize_et(series):

  return(
      series.astype(str)
      .str.strip()
      .str.lower()
      .str.replace("i̇", "i", regex=False)
      .str.replace("ı", "i", regex=False)
      .str.replace("ö", "o", regex=False)
      .str.replace("ü", "u", regex=False)
      .str.replace("ç", "c", regex=False)
      .str.replace("ş", "s", regex=False)
      .str.replace("ğ", "g", regex=False)
  )

In [235]:
#6. Şehir sütunundaki tutrasız verileri düzeltme
df["sehir"] = metin_normalize_et(df["sehir"])
df["sehir"].unique()

array(['istanbul', 'gaziantep', 'kayseri', 'antalya', 'konya', 'ankara',
       'bursa', 'trabzon', 'adana', 'mersin', 'kocaeli', 'izmir',
       'eskisehir', 'samsun'], dtype=object)

In [236]:
sehir_duzeltme_haritasi = {
    "istanbul": "İstanbul",
    "ankara": "Ankara",
    "izmir": "İzmir",
    "antalya": "Antalya",
    "konya": "Konya",
    "bursa": "Bursa",
    "adana": "Adana",
    "gaziantep": "Gaziantep",
    "mersin": "Mersin",
    "kayseri": "Kayseri",
    "eskisehir": "Eskişehir",
    "samsun": "Samsun",
    "trabzon": "Trabzon",
    "kocaeli": "Kocaeli"
}
df["sehir"] = df["sehir"].replace(sehir_duzeltme_haritasi)
df["sehir"].unique()

array(['İstanbul', 'Gaziantep', 'Kayseri', 'Antalya', 'Konya', 'Ankara',
       'Bursa', 'Trabzon', 'Adana', 'Mersin', 'Kocaeli', 'İzmir',
       'Eskişehir', 'Samsun'], dtype=object)

In [237]:
df["kategori"] = metin_normalize_et(df["kategori"])
df["kategori"].unique()

array(['kozmetik', 'spor', 'kitap', 'elektronik', 'ofis', 'ev ve yasam',
       'ev&yasam'], dtype=object)

In [238]:
kategori_duzeltme_haritasi = {
    "elektronik": "Elektronik",
    "kitap": "Kitap",
    "kozmetik": "Kozmetik",
    "kozmetık": "Kozmetik",
    "spor": "Spor",
    "ev yasam": "Ev Yaşam",
    "ev ve yasam": "Ev Yaşam",
    "ev&yasam": "Ev Yaşam",
    "ofis": "Ofis"
}
df["kategori"] = df["kategori"].replace(kategori_duzeltme_haritasi)
df["kategori"].unique()

array(['Kozmetik', 'Spor', 'Kitap', 'Elektronik', 'Ofis', 'Ev Yaşam'],
      dtype=object)

In [239]:
df["odeme_turu"] = metin_normalize_et(df["odeme_turu"])
df["odeme_turu"].unique()

array(['kredi karti', 'banka karti', 'kapida odeme', 'dijital cuzdan',
       'havale/eft', 'kart', 'eft', 'havale'], dtype=object)

In [240]:
odeme_turu_duzeltme_haritasi = {
    "kredi karti": "Kredi Kartı",
    "kart": "Kredi Kartı",
    "banka karti": "Banka Kartı",
    "dijital cuzdan": "Dijital Cüzdan",
    "kapida odeme": "Kapıda Ödeme",
    "havale": "Havale/EFT",
    "eft": "Havale/EFT",
    "havale/eft": "Havale/EFT"
}
df["odeme_turu"] = df["odeme_turu"].replace(odeme_turu_duzeltme_haritasi)
df["odeme_turu"].unique()

array(['Kredi Kartı', 'Banka Kartı', 'Kapıda Ödeme', 'Dijital Cüzdan',
       'Havale/EFT'], dtype=object)

In [241]:
df["musteri_tipi"] = metin_normalize_et(df["musteri_tipi"])
df["musteri_tipi"].unique()

array(['yeni', 'vip', 'mevcut'], dtype=object)

In [242]:
musteri_tipi_duzeltme_haritasi = {
    "mevcut": "Mevcut",
    "yeni": "Yeni",
    "vip": "VIP"
}
df["musteri_tipi"] = df["musteri_tipi"].replace(musteri_tipi_duzeltme_haritasi)
df["musteri_tipi"].unique()

array(['Yeni', 'VIP', 'Mevcut'], dtype=object)

In [243]:
df["musteri_tipi"].value_counts()

musteri_tipi
Mevcut    716
Yeni      520
VIP       164
Name: count, dtype: int64

In [245]:
# mantıksal olarak hatalı kayıtları incele
#negatif yada anlamsız değerler bzeı kayıtlarda veri kalitesini düşürür
hatali_kayitlar = df[
    (df["adet"] < 0) |
    (df["birim_fiyat"] <= 0) |
    (df["toplam_tutar"] <= 0) |
    (df["teslimat_gunu"] < 0) |
    (df["musteri_puani"] < 0) |
    (df["musteri_puani"] > 5)
]
len(hatali_kayitlar)

2

In [247]:
pd.set_option("display.max_columns", None)
hatali_kayitlar

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
609,SIP100095,MUS1165,2025-10-12 21:31:00,İstanbul,Marmara,Kozmetik,Şampuan,2,190.17,0.10,0.0,Dijital Cüzdan,Mevcut,3.0,6.0,Hayır,0.416,342.31,2025,10,12,Sunday
1008,SIP101290,MUS1225,2024-01-16 21:46:00,Kocaeli,Marmara,Kozmetik,Yüz Temizleme Jeli,2,303.82,0.05,29.9,Kredi Kartı,Yeni,5.0,7.0,Evet,0.287,607.16,2024,1,16,Tuesday

In [248]:
# mantıksal hataları temizle
df = df[
    (df["adet"] > 0) &
    (df["birim_fiyat"] > 0) &
    (df["toplam_tutar"] > 0) &
    (df["teslimat_gunu"] >= 0) &
    (df["musteri_puani"] >= 0) &
    (df["musteri_puani"] <= 5)
]
df.shape

(1398, 22)

In [250]:
df.to_csv("e_ticaret_veri_seti_tekrarlayan_kayıtlar_düzenlendi.csv")